// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  auth

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Owner ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Owner ) UnmarshalJSON([]byte) error { return nil }
func ( Owner ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Owner ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Owner *Owner

func ( Token ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Token ) UnmarshalJSON([]byte) error { return nil }
func ( Token ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Token ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Token *Token
