CREATE TABLE characters (
  id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    TEXT    NOT NULL,
  is_main BOOLEAN NOT NULL
);

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE groups (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE roles (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE tokens (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expires_at    INT  NOT NULL,
  type          TEXT NOT NULL,
  access_token  TEXT NOT NULL,
  refresh_token TEXT NOT NULL
);

CREATE TABLE users_groups (
  user_id  INT REFERENCES users (id) ON UPDATE CASCADE,
  group_id INT REFERENCES groups (id) ON UPDATE CASCADE,
  CONSTRAINT users_groups_pkey PRIMARY KEY (user_id, group_id)
);

CREATE TABLE users_characters (
  user_id      INT REFERENCES users (id) ON UPDATE CASCADE,
  character_id INT REFERENCES characters (id) ON UPDATE CASCADE,
  CONSTRAINT users_characters_pkey PRIMARY KEY (user_id, character_id)
);

CREATE TABLE jobs (
  id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installer_id           INT       NOT NULL,
  facility_id            INT       NOT NULL,
  station_id             INT       NOT NULL,
  activity_id            INT       NOT NULL,
  blueprint_id           INT       NOT NULL,
  blueprint_type_id      INT       NOT NULL,
  blueprint_location_id  INT       NOT NULL,
  output_location_id     INT       NOT NULL,
  runs                   SMALLINT  NOT NULL,
  cost                   FLOAT     NOT NULL,
  licensed_runs          SMALLINT  NOT NULL,
  probability            FLOAT     NOT NULL,
  product_type_id        INT       NOT NULL,
  status                 TEXT      NOT NULL,
  duration               INT       NOT NULL,
  start_date             TIMESTAMP NOT NULL,
  end_date               TIMESTAMP NOT NULL,
  pause_date             TIMESTAMP NOT NULL,
  completed_date         TIMESTAMP NOT NULL,
  completed_character_id INT       NOT NULL,
  successful_runs        SMALLINT  NOT NULL
)