CREATE TABLE characters (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE users (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);

CREATE TABLE groups (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);

CREATE TABLE roles (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);

CREATE TABLE tokens (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expires_at    INT,
  type          TEXT,
  access_token  TEXT,
  refresh_token TEXT
);

CREATE TABLE users_groups (
  user_id  INT REFERENCES users (id) ON UPDATE CASCADE,
  group_id INT REFERENCES groups (id) ON UPDATE CASCADE,
  CONSTRAINT users_groups_pkey PRIMARY KEY (user_id, group_id)
);

CREATE TABLE jobs (
  id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installer_id           INT,
  facility_id            INT,
  station_id             INT,
  activity_id            INT,
  blueprint_id           INT,
  blueprint_type_id      INT,
  blueprint_location_id  INT,
  output_location_id     INT,
  runs                   SMALLINT,
  cost                   FLOAT,
  licensed_runs          SMALLINT,
  probability            FLOAT,
  product_type_id        INT,
  status                 TEXT,
  duration               INT,
  start_date             TIMESTAMP,
  end_date               TIMESTAMP,
  pause_date             TIMESTAMP,
  completed_date         TIMESTAMP,
  completed_character_id INT,
  successful_runs        SMALLINT
)